# Generated by Django 4.2.13 on 2024-07-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organisation_org_id_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.UUIDField(default='<function uuid4 at 0x7f3c3abc1700>', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='<function uuid4 at 0x7f3c3abc1700>', editable=False, unique=True),
        ),
    ]
